App:
  port: 

database:
  dbhost: 
  dbport: 
  username: 
  password: 
  dbname: 

file:
  host:
  port:
  key:
  bucket:
  path_ip:

help:
  path_wa:
  path_ip:

jwt:
  access_token:
  refresh_token:

gemini:
  path: 
  model:

keys:
  fb_verify_token: 
  fb_page_access_token: 
  openai_api_key:
  gemini_api_key: 
